[package]
name = "gorf-kiselyov"
version = "0.1.1"
edition = "2021"
license = "CC0-1.0"
description = "Lambda calulcus backend library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_calculus = "3.3.0"
