[workspace]
members=["gorf-core","gorf-kiselyov","lambda-rt","lambda-rt-test","gorf-gen-core","gorf-gen-macro", "gorf-lcobj", "gorf-blc2", "gorf-blc"]
resolver="2"

[workspace.dependencies]

# lambda_calculus = "3.3.0"

lambda_calculus = {git="https://github.com/portal-co/lambda_calculus.git",branch="pr/no_std",version="*"}


webc = { version = "6.0.0-rc1", default-features = false, features = ["package"] }
cxx = "1.0"
noak="0.6.0"
zip = "2.1.1"

spin-sdk = "3.0.1"
url = { version = "2", features = ["serde"] }
dumpster = "0.1.2"

ipld-core = {version="0.4.1",features=["serde"]}
cid = "0.11.1"

anyhow = "1.0.79"
indexmap = "2.1.0"
ed25519-dalek = "2"
x25519-dalek = "2.0.0"
chacha20poly1305 = "0.10.1"
curve25519-dalek = "4.1.1"
rand = "0.8.5"
thiserror = "1.0.56"
merge-io = "0.3.0"
async-trait = "0.1.77"
dyn-clone = "1.0.16"
embedded-io-async = "0.6.1"
futures = "0.3.30"
minicoroutine = "0.1.3"
pasts = "0.14.3"
expander = "2.0.0"
sha3 = "0.10.8"
once_cell = "1.19.0"
bimap = "0.6.3"
serde_bencode = "0.2.4"
multimap = "0.10.0"
chumsky = {version="0.9.3",default-features=false}
either = "1.8.1"
inventory = "0.3.9"

num-bigint = {default-features=false,version="0.4.3"}
num-traits = {default-features=false,version="0.2.16"}
pqc_kyber = "0.7.1"
paste = "1.0.14"
shlex = "1.3.0"



serde = { version = "1.0", features = ["derive","alloc"], default-features = false }

whisk = "0.12.0"

embedded-io-adapters = {version="0.6.1",features=["futures-03"]}
# more-waffle={path="./ratpack/more-waffle"}

postcard = {version="1.0.8",features=["alloc","use-std"]}

wasmi = "0.31.1"
wasm_runtime_layer = { version = "0.4.0" }


syn-serde = { version = "0.3", features = ["json"] }
syn = { version = "2", features = ["full"] }
proc-macro2 = "1.0.78"
quote = "1.0.35"

libp2p = "0.53.2"
libp2p-stream = "0.1.0-alpha"

iroh-net = "0.12.0"
quinn = {version="0.10.2",features=["futures-io"]}



ic-cdk = "0.12.1"

arti-client = {version="0.14.1",features=["onion-service-service","onion-service-client"]}
tor-hsservice = "=0.8.0"
tor-rtcompat = "=0.10.0"
tor-cell = "0.16.1"
tor-hscrypto = "0.6.1"

iced-x86 = {version="1.21.0",features=["code_asm"]}
hyper = {version="1.2.0",features=["http1","server"]}
hyper-util = {version="0.1.3",features=["http1","server","tokio"]}
hyper-futures = "0.1.1"
axum = "0.7.5"
fix-hidden-lifetime-bug = "=0.2.2"

swc_atoms = "2.0.0"
swc_common = "4.0.0"
swc_ecma_ast = "4.0.0"
swc_ecma_compat_es2015 = "5.0.0"
swc_ecma_minifier = "5.0.0"
swc_ecma_transforms_base = "5.0.0"
swc_ecma_utils = "5.0.0"
swc_ecma_visit = "4.0.0"


[profile.release]
strip = "debuginfo"
