[package]
name = "gorf-blc2"
version = "0.2.0-pre.0"
edition = "2021"
license = "CC0-1.0"
description = "Lambda calulcus backend library"

[dependencies]
bitvec = "1.0.1"
lambda_calculus.workspace = true
