[package]
name = "gorf-lcobj"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
description = "Lambda calulcus backend library"

[dependencies]
gorf-core = { version = "0.1.0", path = "../gorf-core" }
serde = { workspace = true, features = ["derive"] }
